# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop
# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'esaudeunb Azure Container Registry'
    repository: 'esaudebackend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile.prod'
    tags: 'hml'
  
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SONARCLOUD_CONNECTION'
    organization: 'fga-eps-mds-1'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'fga-eps-mds_2020.1-eSaudeUnB-BackEnd'
    cliSources: '.'