version: '3.8'

networks:
    esaude-net:

services:

    e-saude-backend:
        build:
            context: .
            dockerfile: Dockerfile
        image: e-saude-backend
        ports:
            - 8000:8000
        volumes:
            - '.:/app'
            - '/app/node_modules'
        networks:
            - esaude-net

    db:
        image: postgres:12.4
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: esaude-db
        ports:
            - 5432:5432
        networks:
            - esaude-net