version: '3.8'

services:

    e-saude-backend:
        build:
            context: .
            dockerfile: Dockerfile.prod
        image: e-saude-backend
        ports:
            - 8000:8000
        environment:
            MONGO_URI: mongodb://root:esaude@mongo:27017
        depends_on:
            - mongo

    mongo:
        image: mongo:4.4.1
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: esaude